package git

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/techspeque/metis/internal/config"
	"github.com/techspeque/metis/internal/slice"
)

// FormatCommitMessage creates a commit message following the configured format.
// Default format: {prefix}({slice_id}): {message}
func FormatCommitMessage(cfg *config.Config, sliceID, prefix, message string) string {
	format := cfg.Commits.Format
	if format == "" {
		format = "{prefix}({slice_id}): {message}"
	}

	r := strings.NewReplacer(
		"{prefix}", prefix,
		"{slice_id}", sliceID,
		"{message}", message,
	)
	return r.Replace(format)
}

// InferPrefix returns the default commit prefix for a given work type.
func InferPrefix(wt slice.WorkType) string {
	return wt.CommitPrefix()
}

// ValidatePrefix checks if a prefix is in the allowed list.
func ValidatePrefix(cfg *config.Config, prefix string) error {
	for _, p := range cfg.Commits.Prefixes {
		if p == prefix {
			return nil
		}
	}
	return fmt.Errorf("invalid commit prefix %q (allowed: %s)", prefix, strings.Join(cfg.Commits.Prefixes, ", "))
}

// StripAttribution removes AI attribution lines from a commit message:
// Co-Authored-By trailers, "Generated with/by" lines, and robot-emoji
// banners. It deliberately does NOT match bare model/tool names as
// substrings — that corrupted legitimate subjects like "reset cursor
// position" or "fix codex parsing".
func StripAttribution(message string) string {
	lines := strings.Split(message, "\n")
	var clean []string

	for i, line := range lines {
		// The subject line is never attribution — stripping it corrupted
		// legitimate subjects and aborted commits with empty messages.
		if i == 0 {
			clean = append(clean, line)
			continue
		}
		lower := strings.ToLower(strings.TrimSpace(line))

		// Skip Co-Authored-By lines
		if strings.HasPrefix(lower, "co-authored-by:") {
			continue
		}

		// Skip "Generated with/by" lines and robot-emoji banners
		if strings.HasPrefix(lower, "generated with") || strings.HasPrefix(lower, "generated by") {
			continue
		}
		if strings.Contains(line, "\U0001F916") {
			continue
		}

		// Skip model-name mentions only when paired with an attribution
		// verb — a bare substring match corrupted legitimate subjects
		// like "reset cursor position" or "fix codex parsing".
		if containsModelName(lower) && containsAttributionVerb(lower) {
			continue
		}

		clean = append(clean, line)
	}

	// Trim trailing empty lines
	for len(clean) > 0 && strings.TrimSpace(clean[len(clean)-1]) == "" {
		clean = clean[:len(clean)-1]
	}

	return strings.Join(clean, "\n")
}

// containsModelName reports whether a line mentions a known AI model/tool.
func containsModelName(lower string) bool {
	for _, name := range []string{
		"claude", "gpt-4", "gpt-3", "gpt4", "gpt3",
		"openai", "anthropic", "codex", "copilot", "cursor", "aider",
	} {
		if strings.Contains(lower, name) {
			return true
		}
	}
	return false
}

var attributionVerbRe = regexp.MustCompile(`\b(assisted|assistance|generated|co-authored|written by|created by|authored by|powered by|with the help of|used)\b`)

// containsAttributionVerb reports whether a line reads as attribution
// rather than as a description of the change itself. Whole-word matches
// only — substring matching flagged "unused", "caused", "assist mode".
func containsAttributionVerb(lower string) bool {
	return attributionVerbRe.MatchString(lower)
}
