run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - gofmt
    - gocritic
    - revive

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-tags:
      - style
      - experimental
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-dirs:
    - testdata
  max-issues-per-linter: 50
  max-same-issues: 5
